name: paperlink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  file_picker: ^10.3.8
  pdfx: ^2.9.2  # For PDF viewing
  photo_view: ^0.15.0  # For image zooming
  path_provider: ^2.1.0  # For file system access

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

# APP ICON CONFIGURATION
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/TEST.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/TEST.png